name: 'JLU autocheck bot'

on:
  push:
  schedule:
    - cron: '0 12 * * *'  # utc+8 21:00
    - cron: '0 23 * * *'  # utc+8 7:00
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.9.0]
    
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - name: 'Setup python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests lxml bs4 
      - name: 'Print version'
        run: pip -V
      - name: 'Check'
        env:
          USERNAME: ${{ secrets.MY_USERNAME }}
          PASSWORD: ${{ secrets.MY_PASSWORD }}
          GRADE: ${{ secrets.MY_GRADE }}
        run: python main.py --user $USERNAME --pwd $PASSWORD --grade $GRADE
